### ISSUE TITLE
Moon underfoot time is always incorrect.

### ISSUE THREAD

**Issue by mb12** [dugb/solunar#1]
Run with the following parameters.  It prints moon underfoot at 0:54. It should be 05:20 (or close to it). Its off by almost 5 hours.

Input Year ( yyyy ) : 2018
Input Month ( mm ) : 3
Input Day ( dd ) : 22
Input Longitude (- is west) : -121.880779
Input Latitude (- is south) : 37.33085
Input Time zone offset ( EST = -5 ) : -7

Solunar data for 2018 / 3 / 22

SUN
 rise = 7:08
does not transit
 set = 19:22
MOON
 rise = 10:38
 transit = 17:46
does not set
 under foot = 0:54
 phase is waxing crescent, 29.4% illuminated, 5.1 days since new

Minor Times
00:00 - 00:00
9:38 - 11:38

Major Times
00:00 - 00:00
16:16 - 19:16

Todays action is rated a 1 (scale is 0 thru 5, 5 is the best)

**Comment by dugb** [comment]
Thanks. I'll look into this.

**Comment by dugb** [comment]
this issue has been fixed.

Thank you,
